# SonarQube exclusions
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S1118
sonar.issue.ignore.multicriteria.e1.resourceKey=**/navbar-panel-commerce/navbar.tsx
sonar.issue.ignore.multicriteria.e1.resourceKey=**/commerce-home-page.tsx

# Limitar análisis
sonar.sources=src
sonar.tests=
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
